# -*- mode: ruby -*-
# vi: set ft=ruby :

$domains_download = <<-SHELL
mkdir domains
chown vagrant:vagrant domains
curl -sSL https://bitbucket.org/ipc2018-classical/domains/get/89741bb4cdd0.zip | bsdtar xvf - --strip-components=1 -C ./domains
SHELL

$install_dependencies = <<-SHELL
apt-get update
apt-get install vim curl wget unzip git bsdtar -y
SHELL

$create_environment = <<-SHELL
mkdir rundir
chown vagrant:vagrant rundir
wget https://raw.githubusercontent.com/zerooneit/maestria-info/main/razonamiento-planeacion-automatica/planners-env

if [ -f .bashrc ]; then
  echo 'source planners-env' >> .bashrc
fi
SHELL


Vagrant.configure("2") do |config|
  config.vm.box = "sylabs/singularity-3.5-ubuntu-bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 2
  end

  config.vm.provision "shell", inline: $install_dependencies
  config.vm.provision "shell", inline: $domains_download
  config.vm.provision "shell", inline: $create_environment
end