# -*- mode: ruby -*-
# vi: set ft=ruby :

$domains_download = <<-SHELL
wget https://bitbucket.org/ipc2018-classical/domains/get/89741bb4cdd0.zip
mkdir domains
unzip ./89741bb4cdd0.zip -d domains

SHELL

$install_dependencies = <<-SHELL
apt-get update
apt-get install vim curl wget unzip git -y
SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "sylabs/singularity-3.5-ubuntu-bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 2
  end

  config.vm.provision "shell", inline: $install_dependencies
  config.vm.provision "shell", inline: $domains_download
end